print("")
print(" a  =  ? ")
print(" c  =  b ")
print("")
print("  a x b ")
print(" --------  =  ?")
print("    c ")
print("")
a = int(input("Enter the first(a) number number: "))
c = int(input("Enter the second(c) number number: "))
b = int(input("Enter the third(b) number number: "))
d = (a*b)/c
print("The result is: ",d)
